require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.1'

prepare_react_native_project!

use_modular_headers!

$RNFirebaseAsStaticFramework = true

target 'ChatApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_config|
        build_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
        build_config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'
        build_config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        build_config.build_settings['GCC_CXX_LANGUAGE_STANDARD'] = 'c++17'
      end
    end
  end
end
